"""一次性初始化 Letta 的 PostgreSQL 库表。

letta 0.16 的 pip wheel 不带 alembic 迁移，server 启动时不建表（默认假设
用官方 docker 镜像或 Letta Desktop 初始化过的库），本地裸跑要先执行：

    .venv/bin/python init_db.py

前提：.env 里的 LETTA_PG_URI 指向已建好、装了 pgvector 扩展的库。
"""

import os

from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env"))

from sqlalchemy import create_engine

import letta.orm  # noqa: F401  向 Base.metadata 注册全部模型
from letta.database_utils import get_database_uri_for_context
from letta.orm.base import Base
from letta.settings import settings

uri = get_database_uri_for_context(settings.letta_pg_uri, "sync")
# pg8000 不认识 ?sslmode=... 这类 libpq 参数（asyncpg 路径才需要），剥掉
uri = uri.split("?")[0]
engine = create_engine(uri)
Base.metadata.create_all(engine)

# messages.sequence_id 在 ORM 里是 FetchedValue（自增由官方 alembic 迁移建），
# create_all 建不出来，手动补 IDENTITY
from sqlalchemy import text

with engine.begin() as conn:
    is_identity = conn.execute(
        text(
            "SELECT is_identity FROM information_schema.columns "
            "WHERE table_name='messages' AND column_name='sequence_id'"
        )
    ).scalar()
    if is_identity == "NO":
        conn.execute(
            text("ALTER TABLE messages ALTER COLUMN sequence_id ADD GENERATED BY DEFAULT AS IDENTITY")
        )
        print("已给 messages.sequence_id 补 IDENTITY")

print(f"已建表 {len(Base.metadata.tables)} 张 → {settings.letta_pg_uri.split('@')[-1]}")
